### PR TITLE
Allow network to be passed to handler

### PR DESCRIPTION
**Pull request by David-Hari**
...so that multiple device profiles can use the same node.

Also a few other minor changes, including resolving #3.

### CODE REVIEW

**Comment by mch** [comment]
This breaks a number of unit tests that don't yet pass the network in. You can run the tests with `python -m unittest discover`. The demos also need to be updated.

**Comment by mch** [comment]
It might be good to make passing in the network optional, using a default argument of None, and then test if it is None and create the network if necessary.

**Comment by David-Hari** [comment]
Yeah, sorry, I forgot about that. I'm just doing that now.
As for making it optional, I think it's probably something that the caller should be responsible for, like creating the Node.

**Comment by David-Hari** [comment]
I updated the unit tests, but I get `ImportError: No module named 'fakes'`. How do relative imports work?

**Comment by mch** [comment]
I found some commits on another computer which I pushed and caused some merge conflicts in your branch. I've fixed that up in another branch: https://github.com/mch/python-ant/tree/David-Hari-master

We can probably just merge that and move forward, or you could cherry pick or merge that branch into this one. 

I had a problem with relative imports at one point, but I can't remember what I did to fix them. I'm not having any problem running the tests with python 2.7 here, so I'm ok to merge it.

**Pull request merged**
